### ISSUE TITLE
Unpackaged extension instructions

### ISSUE THREAD

**Issue by danyshaanan** [rotembcohen/haaretzpass#3]
Hi Rotem.

Great extension!

In case this will fit in your Q&A section or in a wiki page, here are instructions on how to install from source:

* Download and extract this repo as [a zip file](https://github.com/rotembcohen/haaretzpass/archive/master.zip).
* Enter `chrome://extensions/` to your chrome browser's address bar.
* Make sure that the `developer mode` checkbox is checked.
* Click the `Load unpackaged extension...` button.
* Select the `Source` directory from within the extracted zip file.

If you'd say where it should be, I'd be happy to create a PR.

**Comment by rotembcohen** [comment]
I have to say I'm not updated any more about whether or not Chrome allows for developer extensions. Which chrome version did you get this to work on?

**Comment by danyshaanan** [comment]
I'd be surprised if they would limit that option.
I'm on Chrome 60.0.3112.113. (while latest is 61).

**Comment by rotembcohen** [comment]
Well, they actually did (at least for a while). I will need to check whether or not it works for me and only after that change the Readme file if it does. Will update when I'll get around to it.

Thank you, though!

**Comment by rotembcohen** [comment]
Repository no longer active.
